# Generated by Django 6.0 on 2026-01-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
